import { Router } from "express";
import passport from "passport";
import { Strategy as GoogleStrategy } from "passport-google-oauth20";
import { db } from "../db/index.js";
import { users, userChapters } from "../db/schema.js";
import { eq } from "drizzle-orm";
import { v4 as uuidv4 } from "uuid";
import type { User } from "../../types/index.js";
import crypto from "crypto";

const accountsRouter = Router();

// Helper functions for password hashing
const createSalt = () => crypto.randomBytes(16).toString('hex');
const hashPassword = (password: string, salt: string) =>
  crypto.pbkdf2Sync(password, salt, 1000, 64, 'sha512').toString('hex');

// Manual Registration
accountsRouter.post("/register", async (req, res, next) => {
  try {
    const { email, password, name } = req.body;
    if (!email || !password || !name) {
      return res.status(400).json({ error: "Missing required fields" });
    }

    const existing = await db.select().from(users).where(eq(users.email, email)).limit(1);
    if (existing.length > 0) {
      return res.status(400).json({ error: "Email already registered" });
    }

    const salt = createSalt();
    const hashedPassword = hashPassword(password, salt);
    // id is auto-generated by defaultRandom() in schema, but we can provide it too if we want.
    // user_id in schema is 'id' but we used uuidv4() in google strategy manually.
    // The schema defines id: uuid("id").primaryKey().defaultRandom().
    // Let's rely on uuidv4() to coincide with Google Strategy usage.
    const userId = uuidv4();

    const [newUser] = await db.insert(users).values({
      id: userId,
      email,
      name,
      password: hashedPassword,
      salt
    }).returning();

    req.login(newUser, (err) => {
      if (err) return next(err);
      return res.json({ user: newUser });
    });

  } catch (err) {
    console.error("Register error:", err);
    res.status(500).json({ error: "Registration failed" });
  }
});

// Manual Login
accountsRouter.post("/login", async (req, res, next) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) {
      return res.status(400).json({ error: "Missing credentials" });
    }

    const [user] = await db.select().from(users).where(eq(users.email, email)).limit(1);

    if (!user || !user.password || !user.salt) {
      return res.status(401).json({ error: "Invalid credentials" });
    }

    const hashedPassword = hashPassword(password, user.salt);
    if (hashedPassword !== user.password) {
      return res.status(401).json({ error: "Invalid credentials" });
    }

    req.login(user, (err) => {
      if (err) return next(err);
      return res.json({ user });
    });

  } catch (err) {
    console.error("Login error:", err);
    res.status(500).json({ error: "Login failed" });
  }
});

if (process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET) {
  passport.use(
    new GoogleStrategy(
      {
        clientID: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET,
        callbackURL: "/api/auth/google/callback",
        passReqToCallback: true,
      },
      async (req, accessToken, refreshToken, profile, done) => {
        try {
          const userId = uuidv4();
          const email = profile.emails?.[0]?.value;
          const name = profile.displayName;

          if (!email) {
            return done(new Error("Email is required"), undefined);
          }

          if (!name) {
            return done(new Error("Name is required"), undefined);
          }
          const userInfo = {
            user_id: userId,
            name: name,
            email: email,
          };

          let user = await db.select().from(users).where(eq(users.email, userInfo.email));
          if (user.length === 0) {
            const [newUser] = await db.insert(users).values(userInfo).returning();
            req.session.accessToken = accessToken;
            req.session.refreshToken = refreshToken;
            return done(null, newUser);
          }
          req.session.accessToken = accessToken;
          req.session.refreshToken = refreshToken;
          return done(null, user[0]);
        } catch (error) {
          console.error("Error in Google OAuth callback:", error);
          return done(error as Error, undefined);
        }
      }
    )
  );
} else {
  console.warn("Google OAuth credentials not found. Set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in .env");
}

passport.serializeUser((user: any, done) => {
  done(null, user);
});

passport.deserializeUser((user: any, done) => {
  done(null, user);
});

accountsRouter.get(
  "/google",
  passport.authenticate("google", { scope: ["profile", "email"] })
);

accountsRouter.get(
  "/google/callback",
  (req, res, next) => {
    const failureRedirect = `${process.env.FRONTEND_URL || "http://localhost:5173"}/login`;
    passport.authenticate("google", { failureRedirect })(req, res, next);
  },
  async (req, res) => {
    const frontendUrl = process.env.FRONTEND_URL || "http://localhost:5173";

    const user = req.user as User;
    if (!user) {
      return res.redirect(`${frontendUrl}/login`);
    }

    // Fetch the user from DB
    const [userEntry] = await db.select().from(users).where(eq(users.email, user.email));

    if (!userEntry) {
      // Safety check: should rarely happen
      return res.redirect(`${frontendUrl}/login`);
    }

    // Check if user needs to complete setup
    if (!userEntry.isProfileComplete) {
      return res.redirect(`${frontendUrl}/setup`);
    }

    // User already has profile, redirect to dashboard
    return res.redirect(`${frontendUrl}/dashboard`);
  }
);


accountsRouter.get("/me", async (req, res) => {
  const user = req.user as User;
  if (!user) {
    const frontendUrl = process.env.FRONTEND_URL || "http://localhost:5173";
    return res.redirect(`${frontendUrl}/login`);
  }
  const userEntry = await db.select().from(users).where(eq(users.email, user.email)).limit(1);
  res.json({ user: userEntry[0] })
});

accountsRouter.put("/me", async (req, res) => {
  if (!req.isAuthenticated() || !req.user) {
    return res.status(401).json({ error: "Not authenticated" });
  }

  try {
    const { profile, curriculumId, classId } = req.body;
    const user = req.user as User;

    // Validate required fields for new profile structure
    if (!profile) {
      return res.status(400).json({ error: "Profile data is required" });
    }
    if (!profile.curriculumId) {
      return res.status(400).json({ error: "Curriculum is required" });
    }
    if (!profile.classId) {
      return res.status(400).json({ error: "Class is required" });
    }
    if (!Array.isArray(profile.chapterIds) || profile.chapterIds.length === 0) {
      return res.status(400).json({ error: "At least one chapter is required" });
    }

    // Get user ID from email
    const [existingUser] = await db
      .select()
      .from(users)
      .where(eq(users.email, user.email))
      .limit(1);

    if (!existingUser) {
      return res.status(404).json({ error: "User not found" });
    }

    // Update user in DB with new schema
    const [updatedUser] = await db
      .update(users)
      .set({
        profile: profile,
        curriculumId: curriculumId || profile.curriculumId,
        classId: classId || profile.classId,
        isProfileComplete: true,
        updatedAt: new Date()
      })
      .where(eq(users.email, user.email))
      .returning();

    // Update user chapters (delete old, insert new)
    await db.delete(userChapters).where(eq(userChapters.userId, existingUser.id));

    if (profile.chapterIds.length > 0) {
      await db.insert(userChapters).values(
        profile.chapterIds.map((chapterId: string) => ({
          userId: existingUser.id,
          chapterId,
        }))
      );
    }

    console.log('Updated user:', updatedUser);

    // Update session with new user data
    req.user = updatedUser as any;

    // Save session to ensure persistence
    req.session.save((err) => {
      if (err) {
        console.error('Session save error:', err);
      }
    });

    res.json({ user: updatedUser });
  } catch (error) {
    console.error("Error updating user profile:", error);
    res.status(500).json({ error: "Failed to update profile" });
  }
});

accountsRouter.put("/preferences", async (req, res) => {
  if (!req.isAuthenticated() || !req.user) {
    return res.status(401).json({ error: "Not authenticated" });
  }

  try {
    const { language, accessibility } = req.body as {
      language?: string;
      accessibility?: Record<string, unknown>;
    };
    const user = req.user as User;

    const [existingUser] = await db
      .select()
      .from(users)
      .where(eq(users.email, user.email))
      .limit(1);

    if (!existingUser) {
      return res.status(404).json({ error: "User not found" });
    }

    const mergedProfile = {
      ...(existingUser.profile || {}),
      ...(accessibility ? { accessibility } : {}),
      ...(language ? { language } : {}),
    } as import("../../types/index.js").UserProfile;

    const [updatedUser] = await db
      .update(users)
      .set({
        profile: mergedProfile,
        updatedAt: new Date(),
      })
      .where(eq(users.email, user.email))
      .returning();

    req.user = updatedUser as any;
    req.session.save(() => { });

    return res.json({ user: updatedUser });
  } catch (error) {
    console.error("Error updating preferences:", error);
    return res.status(500).json({ error: "Failed to update preferences" });
  }
});

accountsRouter.post("/logout", (req, res) => {
  req.logout((err) => {
    if (err) {
      return res.status(500).json({ error: "Logout failed" });
    }
    req.session.destroy(() => {
      res.json({ message: "Logged out successfully" });
    });
  });
});

/**
 * GET /api/auth/admin-check
 * Check if the current user is an admin
 */
accountsRouter.get("/admin-check", async (req, res) => {
  if (!req.isAuthenticated() || !req.user) {
    return res.json({ isAdmin: false });
  }

  const userEmail = (req.user as any)?.email;

  try {
    const fs = await import("fs");
    const path = await import("path");
    const adminFilePath = path.join(process.cwd(), "admins.json");

    if (!fs.existsSync(adminFilePath)) {
      return res.json({ isAdmin: false });
    }

    const fileContent = fs.readFileSync(adminFilePath, "utf-8");
    const adminEmails: string[] = JSON.parse(fileContent);

    if (!Array.isArray(adminEmails)) {
      return res.json({ isAdmin: false });
    }

    const isAdmin = userEmail && adminEmails.map(e => e.trim().toLowerCase()).includes(userEmail.toLowerCase());
    return res.json({ isAdmin: !!isAdmin });
  } catch (error) {
    console.error("Error checking admin status:", error);
    return res.json({ isAdmin: false });
  }
});

export default accountsRouter;
